"""Unified configuration system for urpm-ng.

Loads settings from INI-style config files with drop-in override support:

    /etc/urpm/urpm.cfg              — Main configuration file
    /etc/urpm/conf.d/*.cfg          — Drop-in overrides (alphabetical order)

Later files override earlier ones (per section+key).  Drop-in files in
``conf.d/`` are loaded after ``urpm.cfg``, so they always win.

In dev mode, the config directory is ``<project_root>/data/etc/urpm/``
if it exists, falling back to ``/etc/urpm/``.

File format (standard INI via configparser)::

    [resolver]
    suggests_as_recommends = true
    install_recommends = true

    [download]
    parallel = 4
    timeout = 30
    min_servers = 2

Settings are exposed as typed dataclass attributes via :func:`get_settings`.
"""

import configparser
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

# System config paths
SYSTEM_CONFIG_DIR = Path("/etc/urpm")
SYSTEM_CONFIG_FILE = SYSTEM_CONFIG_DIR / "urpm.cfg"
SYSTEM_CONFDIR = SYSTEM_CONFIG_DIR / "conf.d"

# Cache
_cached_settings: Optional["Settings"] = None


# ─── Settings dataclasses ───────────────────────────────────────────────

@dataclass
class ResolverSettings:
    """Dependency resolver behaviour."""

    suggests_as_recommends: bool = False
    """Treat @suggests@ from synthesis as Recommends.

    genhdlist2 maps RPM Recommends to @suggests@ in synthesis files.
    When True, the resolver loads them as SOLVABLE_RECOMMENDS so they
    are auto-installed (urpmi-compatible behaviour).
    Set to False when all media are generated by ``urpm genmedia``.
    """

    install_recommends: bool = True
    """Automatically install Recommended packages (like DNF default)."""


@dataclass
class DownloadSettings:
    """Download behaviour."""

    parallel: int = 4
    """Maximum number of simultaneous downloads."""

    timeout: int = 30
    """Default HTTP timeout in seconds for downloads."""

    min_servers: int = 2
    """Minimum number of servers to retrieve per media during setup."""

    max_per_server: int = 2
    """Maximum simultaneous downloads from a single server (guard-rail)."""


@dataclass
class TransactionSettings:
    """Transaction execution behaviour.

    All commands use **smart sync** by default: the parent waits for package
    extraction to complete, then returns immediately while post-install
    triggers (file triggers, ``%posttrans``) continue in the background.

    Passing ``--sync`` on the CLI forces **full sync**: the parent waits for
    everything including triggers, displaying human-readable descriptions.
    Full sync is also forced automatically when packages providing
    ``should-restart:system`` are detected (kernel, glibc, systemd, …).

    No per-command mode settings are needed — the ``--sync`` flag and
    automatic should-restart detection handle all cases.
    """
    pass


@dataclass
class DaemonSettings:
    """Daemon (urpmd) behaviour."""

    discovery_interfaces: str = "all"
    """Network interfaces for P2P discovery broadcasts.

    ``all`` broadcasts on every active interface with a broadcast address
    (excludes loopback).  A comma-separated list of interface names
    (e.g. ``eth0,vboxnet0``) restricts broadcasts to those interfaces.
    """


@dataclass
class Settings:
    """Top-level urpm-ng settings, assembled from config files."""

    resolver: ResolverSettings = field(default_factory=ResolverSettings)
    download: DownloadSettings = field(default_factory=DownloadSettings)
    transaction: TransactionSettings = field(default_factory=TransactionSettings)
    daemon: DaemonSettings = field(default_factory=DaemonSettings)

    # Path that was actually loaded (for diagnostics / ``urpm config show``)
    _config_dir: Path = field(default=SYSTEM_CONFIG_DIR, repr=False)
    _loaded_files: list = field(default_factory=list, repr=False)


# ─── Parsing helpers ────────────────────────────────────────────────────

_BOOL_TRUE = frozenset({"true", "yes", "1", "on"})
_BOOL_FALSE = frozenset({"false", "no", "0", "off"})


def _as_bool(value: str) -> bool:
    """Convert a config string to bool (case-insensitive)."""
    v = value.strip().lower()
    if v in _BOOL_TRUE:
        return True
    if v in _BOOL_FALSE:
        return False
    raise ValueError(f"Not a boolean value: {value!r}")


def _as_int(value: str) -> int:
    """Convert a config string to int."""
    return int(value.strip())


# ─── Config loading ─────────────────────────────────────────────────────

def _find_config_dir() -> Path:
    """Find the active configuration directory.

    Detection order:
    1. ``_get_project_root()`` (from ``sys.argv[0]``, e.g. ``bin/urpm``)
    2. Module-relative (``urpm/core/settings.py`` → project root) —
       works under pytest, IDE runners, and any non-bin/ invocation
    3. System ``/etc/urpm/``

    Steps 1-2 look for ``<root>/data/etc/urpm/`` and use it if present.
    This means a source checkout with the config templates always wins
    over the system path, which is the desired dev-time behaviour.
    """
    from .config import _get_project_root

    # Try argv-based root (bin/urpm, bin/urpmd)
    root = _get_project_root()
    if root:
        dev_dir = root / "data" / "etc" / "urpm"
        if dev_dir.is_dir():
            return dev_dir

    # Fallback: module-relative (pytest, IDE, direct python -c …)
    module_root = Path(__file__).resolve().parent.parent.parent
    dev_dir = module_root / "data" / "etc" / "urpm"
    if dev_dir.is_dir():
        return dev_dir

    return SYSTEM_CONFIG_DIR


def _collect_config_files(config_dir: Path) -> list[Path]:
    """Return ordered list of config files to load.

    Order: ``urpm.cfg`` first, then ``conf.d/*.cfg`` sorted alphabetically.
    Missing files / directories are silently skipped.
    """
    files: list[Path] = []

    main = config_dir / "urpm.cfg"
    if main.is_file():
        files.append(main)

    confdir = config_dir / "conf.d"
    if confdir.is_dir():
        for f in sorted(confdir.iterdir()):
            if f.suffix == ".cfg" and f.is_file():
                files.append(f)

    return files


def _load_raw(config_dir: Path) -> tuple[configparser.ConfigParser, list[Path]]:
    """Parse all config files and return the merged ConfigParser."""
    cp = configparser.ConfigParser(interpolation=None)
    # Preserve key casing (we use snake_case everywhere)
    cp.optionxform = str  # type: ignore[assignment]

    files = _collect_config_files(config_dir)
    loaded: list[Path] = []
    for f in files:
        try:
            cp.read(str(f), encoding="utf-8")
            loaded.append(f)
        except (configparser.Error, OSError):
            pass  # Skip malformed / unreadable files silently

    return cp, loaded


def _apply(cp: configparser.ConfigParser, settings: Settings) -> None:
    """Apply parsed config values to the Settings object.

    Unknown sections or keys are silently ignored (forward-compat).
    """
    # [resolver]
    if cp.has_section("resolver"):
        for key, raw in cp.items("resolver"):
            try:
                if key == "suggests_as_recommends":
                    settings.resolver.suggests_as_recommends = _as_bool(raw)
                elif key == "install_recommends":
                    settings.resolver.install_recommends = _as_bool(raw)
            except ValueError:
                pass  # Ignore invalid values

    # [download]
    if cp.has_section("download"):
        for key, raw in cp.items("download"):
            try:
                if key == "parallel":
                    val = _as_int(raw)
                    if 1 <= val <= 32:
                        settings.download.parallel = val
                elif key == "timeout":
                    val = _as_int(raw)
                    if val > 0:
                        settings.download.timeout = val
                elif key == "min_servers":
                    val = _as_int(raw)
                    if val >= 1:
                        settings.download.min_servers = val
                elif key == "max_per_server":
                    val = _as_int(raw)
                    if 1 <= val <= 16:
                        settings.download.max_per_server = val
            except ValueError:
                pass

    # [daemon]
    if cp.has_section("daemon"):
        for key, raw in cp.items("daemon"):
            if key == "discovery_interfaces":
                val = raw.strip()
                if val:
                    settings.daemon.discovery_interfaces = val

    # [transaction] — reserved for future settings; mode fields removed
    # (smart sync is now the default, --sync forces full sync)


# ─── Public API ─────────────────────────────────────────────────────────

def load_settings(config_dir: Path = None) -> Settings:
    """Load settings from config files.

    Args:
        config_dir: Override config directory (for testing).
                    None = auto-detect (dev or system).

    Returns:
        Fully populated Settings instance.
    """
    if config_dir is None:
        config_dir = _find_config_dir()

    settings = Settings(_config_dir=config_dir)
    cp, loaded = _load_raw(config_dir)
    settings._loaded_files = loaded
    _apply(cp, settings)

    return settings


def get_settings() -> Settings:
    """Get the cached global settings (lazy-loaded singleton).

    First call reads config files; subsequent calls return the cache.
    Use :func:`reload_settings` to force a re-read.
    """
    global _cached_settings
    if _cached_settings is None:
        _cached_settings = load_settings()
    return _cached_settings


def reload_settings() -> Settings:
    """Force re-read of config files and return fresh Settings."""
    global _cached_settings
    _cached_settings = load_settings()
    return _cached_settings


def format_settings(settings: Settings = None) -> str:
    """Format current effective settings as human-readable text.

    Used by ``urpm config show``.
    """
    if settings is None:
        settings = get_settings()

    lines = []
    lines.append(f"# Effective configuration (from {settings._config_dir})")
    if settings._loaded_files:
        lines.append(f"# Loaded files: {', '.join(str(f) for f in settings._loaded_files)}")
    else:
        lines.append("# No config files found — using built-in defaults")
    lines.append("")

    lines.append("[resolver]")
    lines.append(f"suggests_as_recommends = {str(settings.resolver.suggests_as_recommends).lower()}")
    lines.append(f"install_recommends = {str(settings.resolver.install_recommends).lower()}")
    lines.append("")

    lines.append("[download]")
    lines.append(f"parallel = {settings.download.parallel}")
    lines.append(f"timeout = {settings.download.timeout}")
    lines.append(f"min_servers = {settings.download.min_servers}")
    lines.append("")

    lines.append("[transaction]")
    lines.append("# Smart sync is the default; use --sync for full sync")

    lines.append("")
    lines.append("[daemon]")
    lines.append(f"discovery_interfaces = {settings.daemon.discovery_interfaces}")

    return "\n".join(lines)
