"""Qt compatibility layer.

Provides unified imports for PyQt6 and PySide6.
Uses whichever is available, preferring PySide6.
"""

__all__ = [
    "QT_BINDING",
    "Signal",
    "Slot",
    "Qt",
    "QApplication",
    "QMainWindow",
    "QWidget",
    "QDialog",
    "QVBoxLayout",
    "QHBoxLayout",
    "QSplitter",
    "QStatusBar",
    "QPushButton",
    "QLabel",
    "QProgressBar",
    "QLineEdit",
    "QTableView",
    "QAbstractItemView",
    "QHeaderView",
    "QStyledItemDelegate",
    "QStyle",
    "QStyleOptionButton",
    "QAbstractTableModel",
    "QModelIndex",
    "QRect",
    "QSize",
    "QObject",
    "QMetaObject",
    "QMessageBox",
    "QKeySequence",
    "QShortcut",
    "QAction",
    "QMouseEvent",
    "QKeyEvent",
    "QCheckBox",
    "QGroupBox",
    "QTreeWidget",
    "QTreeWidgetItem",
    "QListWidget",
    "QListWidgetItem",
    "QScrollArea",
    "QFrame",
    "QToolButton",
    "QMenu",
    "QColor",
    "QBrush",
    "QFont",
    "QFontMetrics",
    "QTimer",
]

try:
    # Try PySide6 first
    from PySide6.QtCore import (
        Qt,
        Signal,
        Slot,
        QObject,
        QMetaObject,
        QAbstractTableModel,
        QModelIndex,
        QRect,
        QSize,
        QTimer,
    )
    from PySide6.QtWidgets import (
        QApplication,
        QMainWindow,
        QWidget,
        QDialog,
        QVBoxLayout,
        QHBoxLayout,
        QSplitter,
        QStatusBar,
        QPushButton,
        QLabel,
        QProgressBar,
        QLineEdit,
        QTableView,
        QAbstractItemView,
        QHeaderView,
        QStyledItemDelegate,
        QStyle,
        QStyleOptionButton,
        QMessageBox,
        QCheckBox,
        QGroupBox,
        QTreeWidget,
        QTreeWidgetItem,
        QListWidget,
        QListWidgetItem,
        QScrollArea,
        QFrame,
        QToolButton,
        QMenu,
    )
    from PySide6.QtGui import (
        QKeySequence,
        QShortcut,
        QAction,
        QMouseEvent,
        QKeyEvent,
        QColor,
        QBrush,
        QFont,
        QFontMetrics,
    )
    QT_BINDING = "PySide6"

except ImportError:
    # Fall back to PyQt6
    from PyQt6.QtCore import (
        Qt,
        pyqtSignal as Signal,
        pyqtSlot as Slot,
        QObject,
        QMetaObject,
        QAbstractTableModel,
        QModelIndex,
        QRect,
        QSize,
        QTimer,
    )
    from PyQt6.QtWidgets import (
        QApplication,
        QMainWindow,
        QWidget,
        QDialog,
        QVBoxLayout,
        QHBoxLayout,
        QSplitter,
        QStatusBar,
        QPushButton,
        QLabel,
        QProgressBar,
        QLineEdit,
        QTableView,
        QAbstractItemView,
        QHeaderView,
        QStyledItemDelegate,
        QStyle,
        QStyleOptionButton,
        QMessageBox,
        QCheckBox,
        QGroupBox,
        QTreeWidget,
        QTreeWidgetItem,
        QListWidget,
        QListWidgetItem,
        QScrollArea,
        QFrame,
        QToolButton,
        QMenu,
    )
    from PyQt6.QtGui import (
        QKeySequence,
        QShortcut,
        QAction,
        QMouseEvent,
        QKeyEvent,
        QColor,
        QBrush,
        QFont,
        QFontMetrics,
    )
    QT_BINDING = "PyQt6"
