"""``media_info`` XML files must match what genhdlist2 emits.

Legacy urpmi walks the element children of ``<media_info>`` expecting
an ``fn`` attribute on each.  A newline between two of them is a
``#text`` node, which it rejects:

    urpmq -pi megasync
    missing attribute "fn" in tag "#text"

Reported against a media generated by ``urpm genmedia``.  Our three
writers all emitted indented, newline-separated children — and carried
a ``.rpm`` suffix on ``fn`` where genhdlist2 writes the bare NEVRA.

The second divergence never raises: the value parses, matches nothing,
and the lookup simply comes back empty.  It also feeds our own
``appstream_scan``, where ``parse_nevra`` accepts the trailing
``.rpm`` and silently yields ``arch='rpm'``.

The reference format is documented at the top of
:mod:`urpm.core.files_xml` — the parser side had it right all along.
"""

from __future__ import annotations

import lzma
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path

import pytest

from urpm.core.files_xml import (
    write_changelog_xml,
    write_files_xml,
    write_info_xml,
)


@dataclass
class _Pkg:
    """Minimal stand-in for ``RpmMetadata``."""

    filename: str = "testapp-browser-1.0-1.mga10.noarch.rpm"
    files: list = field(default_factory=lambda: ["/usr/bin/testapp"])
    sourcerpm: str = "testapp-browser-1.0-1.mga10.src.rpm"
    url: str = "https://example.invalid/"
    license: str = "MPL"
    description: str = "A test package."
    changelog: list = field(
        default_factory=lambda: [(1647432000, "packager <p> 1.0-1", "- built")]
    )


NEVRA = "testapp-browser-1.0-1.mga10.noarch"


def _write_and_read(writer, tmp_path, packages=None) -> str:
    """Run *writer* and return the decompressed XML text."""
    out = tmp_path / "out.xml.lzma"
    writer(out, packages if packages is not None else [_Pkg(), _Pkg()])
    with lzma.open(out, "rt", encoding="utf-8") as f:
        return f.read()


WRITERS = [
    pytest.param(write_files_xml, "files", id="files"),
    pytest.param(write_info_xml, "info", id="info"),
    pytest.param(write_changelog_xml, "changelogs", id="changelog"),
]


@pytest.mark.parametrize("writer,child_tag", WRITERS)
class TestMediaInfoFormat:

    def test_starts_with_the_xml_declaration(self, writer, child_tag, tmp_path):
        text = _write_and_read(writer, tmp_path)
        assert text.startswith('<?xml version="1.0" encoding="utf-8"?>')

    def test_no_text_nodes_between_element_children(
        self, writer, child_tag, tmp_path,
    ):
        """The regression itself, checked structurally rather than by
        string comparison : parse the document and assert
        ``<media_info>`` carries no text of its own and no tail text
        between children.  Any of those is what legacy urpmi reports as
        « missing attribute "fn" in tag "#text" »."""
        root = ET.fromstring(_write_and_read(writer, tmp_path))
        # Deliberately NOT stripped : whitespace *is* the defect.  A
        # newline between two children is a text node, and stripping
        # before comparing would let exactly the broken output through.
        assert not root.text, (
            f"text node {root.text!r} between <media_info> and its "
            f"first child"
        )
        for child in root:
            assert not child.tail, (
                f"text node {child.tail!r} after <{child.tag}>"
            )

    def test_every_child_carries_fn(self, writer, child_tag, tmp_path):
        """What the legacy parser actually demands of each child."""
        root = ET.fromstring(_write_and_read(writer, tmp_path))
        children = list(root)
        assert children, "no element children written"
        for child in children:
            assert child.tag == child_tag
            assert child.get("fn"), f"<{child.tag}> without fn"

    def test_fn_is_the_bare_nevra(self, writer, child_tag, tmp_path):
        """genhdlist2 writes ``fn="foo-1.0-1.mga10.x86_64"``.  A ``.rpm``
        suffix matches nothing and says nothing."""
        root = ET.fromstring(_write_and_read(writer, tmp_path))
        for child in root:
            assert child.get("fn") == NEVRA
            assert not child.get("fn").endswith(".rpm")

    def test_output_is_well_formed(self, writer, child_tag, tmp_path):
        """Guards the hand-written serialisation against unbalanced
        tags, which the whitespace changes could easily introduce."""
        ET.fromstring(_write_and_read(writer, tmp_path))

    def test_empty_package_list_is_still_valid_xml(
        self, writer, child_tag, tmp_path,
    ):
        root = ET.fromstring(_write_and_read(writer, tmp_path, packages=[]))
        assert root.tag == "media_info"
        assert list(root) == []


class TestFnRegexCompatibility:
    """``extract_nevras_from_files_xml`` scans for ``fn="..."`` with
    double quotes.  Writers using single quotes were invisible to it."""

    def test_fn_uses_double_quotes(self, tmp_path):
        for writer in (write_files_xml, write_info_xml, write_changelog_xml):
            text = _write_and_read(writer, tmp_path)
            assert f'fn="{NEVRA}"' in text, (
                f"{writer.__name__} does not quote fn the way "
                f"extract_nevras_from_files_xml expects"
            )

    def test_extract_nevras_finds_them(self, tmp_path):
        """End-to-end against the real extractor."""
        from urpm.core.files_xml import extract_nevras_from_files_xml
        out = tmp_path / "files.xml.lzma"
        write_files_xml(out, [_Pkg()])
        assert extract_nevras_from_files_xml(out) == {NEVRA}


class TestContentIsPreserved:
    """Removing whitespace must not remove payload."""

    def test_files_are_listed(self, tmp_path):
        out = tmp_path / "files.xml.lzma"
        write_files_xml(out, [_Pkg(files=["/usr/bin/a", "/usr/bin/b"])])
        with lzma.open(out, "rt", encoding="utf-8") as f:
            root = ET.fromstring(f.read())
        listed = [ln.strip() for ln in (root[0].text or "").split("\n")
                  if ln.strip()]
        assert listed == ["/usr/bin/a", "/usr/bin/b"]

    def test_description_survives(self, tmp_path):
        out = tmp_path / "info.xml.lzma"
        write_info_xml(out, [_Pkg(description="Some description.")])
        with lzma.open(out, "rt", encoding="utf-8") as f:
            root = ET.fromstring(f.read())
        assert "Some description." in (root[0].text or "")

    def test_changelog_entries_survive(self, tmp_path):
        out = tmp_path / "changelog.xml.lzma"
        write_changelog_xml(out, [_Pkg()])
        with lzma.open(out, "rt", encoding="utf-8") as f:
            root = ET.fromstring(f.read())
        logs = root[0].findall("log")
        assert len(logs) == 1
        assert logs[0].get("time") == "1647432000"
        assert logs[0].findtext("log_name") == "packager <p> 1.0-1"
        assert logs[0].findtext("log_text") == "- built"
